const API='../.netlify/functions/admin-api';
const $=s=>document.querySelector(s);let token=localStorage.getItem('flerteAdminToken');
function msg(el,text,ok=false){el.textContent=text;el.style.color=ok?'#087d70':'#b33'}
async function api(url,options={}){const headers={...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;return fetch(url,{...options,headers})}
function showPanel(){ $('#login').hidden=true;$('#panel').hidden=false;loadImages(); }
if(token)showPanel();
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const m=$('#loginMsg');msg(m,'A entrar...');try{const r=await fetch(`${API}?action=login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#username').value,password:$('#password').value})});const d=await r.json();if(!r.ok)throw new Error(d.error);token=d.token;localStorage.setItem('flerteAdminToken',token);showPanel()}catch(err){msg(m,err.message)}});
$('#logout').onclick=()=>{localStorage.removeItem('flerteAdminToken');token=null;location.reload()};$('#refresh').onclick=loadImages;
async function loadImages(){const r=await fetch(`${API}?action=list`);const d=await r.json();const g=$('#gallery');g.innerHTML='';if(!d.images?.length){g.innerHTML='<p>Ainda não existem fotos carregadas pelo painel.</p>';return}d.images.forEach(im=>{const el=document.createElement('article');el.className='photo';el.innerHTML=`<img src="${im.url}" alt=""><div><span>${im.name}</span><button class="bg" data-bg="${im.name}">${d.background===im.name?'✓ Background':'Usar no background'}</button><button class="delete" data-name="${im.name}">Eliminar</button></div>`;el.querySelector('[data-bg]').onclick=()=>setBackground(im.name);el.querySelector('[data-name]').onclick=()=>deleteImage(im.name);g.appendChild(el)})}
async function setBackground(name){const r=await api(`${API}?action=background`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});const d=await r.json();if(!r.ok){alert(d.error||'Não foi possível definir o background.');return}loadImages()}
async function deleteImage(name){if(!confirm(`Eliminar ${name}?`))return;const r=await api(`${API}?action=delete&name=${encodeURIComponent(name)}`,{method:'DELETE'});if(r.ok)loadImages();else{const d=await r.json();alert(d.error||'Não foi possível eliminar.')}}
$('#uploadBtn').onclick=async()=>{const input=$('#file'),m=$('#uploadMsg');if(!input.files[0])return msg(m,'Selecione uma imagem.');msg(m,'A preparar imagem...',true);const file=input.files[0];const data=await optimize(file);const name=$('#filename').value.trim()||file.name.replace(/\.[^.]+$/,'');msg(m,'A enviar...',true);const r=await api(`${API}?action=upload`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,type:'image/jpeg',data})});const d=await r.json();if(!r.ok){msg(m,d.error||'Erro no envio.');return}msg(m,'Imagem adicionada com sucesso.',true);input.value='';$('#filename').value='';loadImages()};
function optimize(file){return new Promise((resolve,reject)=>{const img=new Image(),reader=new FileReader();reader.onload=()=>{img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
